### ISSUE TITLE
Add Odin flatpak manifest

### ISSUE THREAD

**Issue by hanaral** [Suzie97/epoch#1]
If you ever want to publish it or speed up testing

**Comment by Suzie97** [comment]
If I can figure out how to access the system time zones without using gweather, sure. I''ll publish it to AppCenter. Still learning ☺️

**Comment by Suzie97** [comment]
I was able to get the local time. It was actually very simple. I was just overthinking 😅 . So yes, the flatpak manifest will be coming soon 👍🏼
