### ISSUE TITLE
Changing the Time Zones of the clocks

### ISSUE THREAD

**Issue by Suzie97** [Suzie97/epoch#2]
In gtk 3 and X11, the popovers cannot be bigger than the window https://gitlab.gnome.org/GNOME/gtk/-/issues/543.

So my original plan was to let the user change the time zone like this:
![Screenshot from 2021-07-18 23-34-47](https://user-images.githubusercontent.com/68198116/126077843-aa7d5ec8-8d6c-4635-bfce-046204421d97.png)

But as you can see, the popover is unusably (if that is even a word) small. This is an essential feature of the app and the entire app wouldn't make much sense without it.

@hanaral, @Abdallah-Moh, any ideas on how to solve this??

**Comment by Suzie97** [comment]
One way we could do this is to use a separate dialog to set it up. But I want the widget to be a single window simple experience.

**Comment by hanaral** [comment]
Are you able to do what elementary Calculator does to show more buttons by growing the window outwards? that way the popover may not be necessary as the picker menu would be a reliable part of the main window an not just a submenu (while it open, it could return to its original size when it is closed)

**Comment by Suzie97** [comment]
> Are you able to do what elementary Calculator does to show more buttons by growing the window outwards? that way the popover may not be necessary as the picker menu would be a reliable part of the main window an not just a submenu (while it open, it could return to its original size when it is closed)

So how do I indicate the parent button of the picker menu? Make the other buttons non interactive when the menu is active?

The popover provides much better UX. I'll look at how wingpanel does this. Because the indicators display popovers with a window really.

**Comment by hanaral** [comment]
@Suzie97 unfortunately I don't think you'll get very far since, afaict, the wingpanel _does_ take up the entire screen. The reason I presume it uses this workaround is because when wingpanel freezes, the entire desktop becomes un-interactable - apart from when in the multitasking overview, which wouldn't be effected by a window.

The idea of having a popover is not bad, but I was suggesting the use of the main window just as the Date & Time panel in settings does - you to also use Granite.ModeButton to separate the different clocks' pages

**Comment by Suzie97** [comment]
> @Suzie97 unfortunately I don't think you'll get very far since, afaict, the wingpanel _does_ take up the entire screen. The reason I presume it uses this workaround is because when wingpanel freezes, the entire desktop becomes un-interactable - apart from when in the multitasking overview, which wouldn't be effected by a window.
> 
> The idea of having a popover is not bad, but I was suggesting the use of the main window just as the Date & Time panel in settings does - you to also use Granite.ModeButton to separate the different clocks' pages

Nice point. I think, i'm going to provide an edit button for each of the different clocks, rather than doing it all in one preferences view. This way, then the edit button for one clock is clicked, the window will switch to the edit view for that clock and thus avoiding any confusion.

**Comment by Suzie97** [comment]
> @Suzie97 unfortunately I don't think you'll get very far since, afaict, the wingpanel _does_ take up the entire screen. The reason I presume it uses this workaround is because when wingpanel freezes, the entire desktop becomes un-interactable - apart from when in the multitasking overview, which wouldn't be effected by a window.
> 
> The idea of having a popover is not bad, but I was suggesting the use of the main window just as the Date & Time panel in settings does - you to also use Granite.ModeButton to separate the different clocks' pages

Nice point. I will be best to use the ModelButton and the grid like in the settings.

**Comment by Suzie97** [comment]
![Screenshot from 2021-07-19 15-18-04](https://user-images.githubusercontent.com/68198116/126140988-95179757-caae-4c0f-9479-3d0e38c21b67.png)

Thanks @hanaral. I'm happy with how the preferences view turned out.
